#!/bin/bash

echo "rm release/website"
rm -rf release/website
mkdir release/website

echo "cp -rf src/* release"
cp -rf src/* release/website

cd release/website

echo "compiling python..."
../Python27/python -OO -m compileall .
rm -rf $(find . -type f -name "*.py" -o -name "*.pyc")
cp ../../src/esafety/wsgi.py esafety/wsgi.py

echo "clean up files..."
rm -rf esafety/wsgi.pyo
rm -rf esafety/settings.pyo
rm -rf esafety/settings_linux.pyo
rm -rf locale/zh_CN/LC_MESSAGES/django.po
rm -rf etraining/sql

echo "publish done"
